### ISSUE TITLE
Add a "Rich Text" field type. Editing a "Rich Text" field type would display a WYSIWYG editor.

### ISSUE THREAD

**Issue by ardeearam** [klaudsol/klaudsol-cms#158]
Add a "Rich Text" field type. 

Editing a "Rich Text" field type would display a WYSIWYG editor.

![Image](https://user-images.githubusercontent.com/1546228/214744493-f0a4e851-bca4-4bac-b9f9-c01b64cb8d2e.png)

![Image](https://user-images.githubusercontent.com/1546228/214744790-2ade0f19-92ca-4d3d-90f7-e60f77306488.png)

**Comment by angeli-mercedes** [comment]
You can use this react library for this:

https://www.npmjs.com/package/react-draft-wysiwyg?activeTab=readme
