### ISSUE TITLE
User, Groups, Roles, and Capabilities Management

### ISSUE THREAD

**Issue by ardeearam** [klaudsol/klaudsol-cms#196]
Why? / Motivation
---

At the moment, there is only one user role, and that user can do anything and everything in the system. This is not suitable for real-world usage. E.g., there should be one set of capabilities for the developer / devops of the system, another one for the highest role that can be given to a non-techy person, and finally another one with the simplest and easiest interface for daily content management purposes.

* We want it to be powerful enough and flexible enough for the development and devOps team to do whatever what is required from the client.
* We want it to be simple and zen enough for non-techy daily users. We need to trim down as many elements, decision-making, and steps as much as possible so that it would be ridiculously easy to use (imagine iPhone or Macbook). It should have a feel to normal users to "just work", and disappear into the background. These guys are busy, and they have more important things to do than to twiddle with a CMS.
* For any users, it should be visually quiet, only providing what is necessary, and no more.

Architecture
---

* We get inspiration from WordPress and Amazon Web Services on how they do their permissions. We adopt a "whitelist" approach to permissions - by default, you cannot do anything. You need to be given a "capability" to be able to do anything. We take capabilities to be as granular as possible so that we can mix and match these capabilities depending on the use case. Examples of capabilities may include `read_contents`, `write_contents`, `read_settings`, `write_setings`, etc.

* We define a "group" as a set of people who has the same set of "capabilities". Some examples may include `System Administrators`, `Administrators`, `Editors`, and `Guests`. If the user is not logged in, we fall back to the capabilities of `Guests`.

* To simplify the design, we do not directly assign the capabilities to users, but to groups. This would also simplify user management as well. 

Database Tables
---
**capabilities**
* A capability must be written as a *verb*
* We expect the entries to be dynamic and ever-growing, as we develop KlaudSol CMS.
* Later, we can use this in the backend via `assertCurrentUserCan('modify_logo')`.
* In the future (not now), we can allow the users to create their own capabilities, thus the `is_system_supplied` column. This is a nice-to-have, especially if we allow plugins to KlaudSol CMS.
* System-supplied capabilities should not be modifiable.

id  | name  | description |is_system_supplied 
---|---|--------------|-----------------------
1 | read_contents | Read contents| 1
2 | write_contents| Add, Update, or Delete contents|1
3 |read_content_types| Read Content types | 1
4 |write_content_types|Add, Update, or Delete content types | 1
5 |read_setttings| Get global setting values | 1 
6 |write_settings| Modify global setting values | 1
7 |modify_logo | Change the logo on the front page, defaults to the KlaudSol logo | 1

**groups**
* A `group` is a collection of people with the same business function.
* Since a group is a collection of people, the group name must be in plural form.
* In the future (no need to implement now), we allow the user to add custom groups.
* System-supplied groups are not modifiable.

id | name | description | is_system_supplied
--|-------|------------|---------------------
1| Super Administrators| Lorem ipsum | 1
2| Administrators| Lorem ipsum | 1
3| Editors| Lorem ipsum | 1
4| Guests| Lorem ipsum | 1

**people_groups**
* Where we assign people to their corresponding groups.
* A person can be a member of more than one group.
* No need for an `id` primary key.
* We use the compound key (people_id, group_id) as the primary key.

people_id | group_id
----|----
1 | 1
2| 2

**group_capabilities**
* Assigns one or more capabilities to one or more groups
* Some future capabilities might need extra parameters for it to work (e.g. you can read the content type `articles` but not `menus`). For now, let's not deal with the scenario, but it's best that we consider them in our database design.
* Usage of this table will be somewhat like `assertCurrentUserCan('read_content_types',  'articles')`

group_id | capabillities_id | params1 | params2 | params3
----------|----------------|----------|----------|---------
3 | 1 | NULL | NULL | NULL
3 | 3 | 'articles' | NULL | NULL 
3 | 4 | 'articles' | NULL | NULL 
3 | 4 | 'menus' | NULL | NULL

Backend (API) functions
---
* New: [`assertUserCan()`](https://github.com/klaudsol/klaudsol-cms/blob/main/lib/Permissions.js)
  * Checks if the current user can perform a capability. Throws an `InsufficientPermissionsError` exception if the user is not allowed. [The `InsufficientPermissionsError` is already in the system.](https://github.com/klaudsol/klaudsol-cms/blob/main/components/errors/InsufficientPermissionsError.js)
  * The `defaultErrorHandler` already returns a status code of `FORBIDDEN` when catching an `InsufficientPermissionsError` (see https://github.com/klaudsol/klaudsol-cms/blob/main/lib/ErrorHandler.js#L21)
  * We adhere to the philosophy of ["Ask forgiveness, not permission"](https://realpython.com/python-lbyl-vs-eafp/#:~:text=EAFP%2C%20or%20easier%20to%20ask,exception%20and%20handle%20it%20appropriately.) when it comes to authorization. 
    * We do not want something like `if(userCan('read_contents'))` in our backend code. We want our code to bail out if they do not have the required capabilities.
  * We should be more particular in our backend permissions policy over our frontend permissions policy. The backend should be water-tight when it comes to authorization matters.
  * If the user is not logged in, `assertUserCan()` behaves as if the logged-in user is a user that is a member of the `Guests` group.
  * Usage:  
    * `assertUserCan('read_contents')` - true if the user can read all contents, throws `InsufficientPermissionsError` if not.
    * `assertUserCan('read_contents') && assertUserCan('read_content_types')` - BOTH `read_contents` AND `read_content_types` are required.
    * `assertUserCan(['read_contents', 'read_content_types'])` - EITHER `read_contents` OR `read_content_types` are required.

* Update: [`People.login()`](https://github.com/klaudsol/klaudsol-cms/blob/main/backend/models/core/People.js#L79)
  *  Return `capabilities` as well. `capabilities` is an array of string capabilities that the recently logged-in user is allowed to have. This information shall be thrown to the frontend.

* Update: [`/api/login`](https://github.com/klaudsol/klaudsol-cms/blob/main/pages/api/login.js#L26)
  * Include  `capabililties` in `req.session.cache`.

Frontend
---

* Update: [`/components/hooks.js`](https://github.com/klaudsol/klaudsol-cms/blob/main/components/hooks.js)
  * Create a new hook named `useCapabilities()` so that you can access the capabilities anywhere in React (without the need to continuously passing `{...props}`.
  
```
export const useCapabilities = () => {
  const cache = useContext(CacheContext);
  return cache?.capabillities ?? [];
};
```

* Finally, in any React component:

```
const capabilities = useCapabilities();
...
return (

  {capabilities.includes('modify_logo') && (
    <div>Hey, you can modify the logo!</div>
  )}
);
```

* Another example, this time a real-world example for the [AppSidebar](https://github.com/klaudsol/klaudsol-cms/blob/0cdf44925009901b66da80caef8e0489dec04017/components/elements/inner/AppSidebar.js#L44): Remove the settings menu item if the user does not have any capabilities to modify them.

```
const capabilities = useCapabilities();
...
(capabilities.includes('write_setttings')  ? {
   title: "Settings",
   path: "/admin/settings",
   icon: <RiSettings3Line className='sidebar_button_icon'/>
 }: null),  //Create a filter at the bottom to remove null values from the array
```

**Comment by angeli-mercedes** [comment]
FIgma design:
https://www.figma.com/file/f5PwEKzWnxJwH4wcCyRdkZ/KlaudSol-CMS?node-id=102%3A2&t=39PQh53i9VdrOPJ3-0

![Image](https://user-images.githubusercontent.com/101687552/220821138-a96d82cf-fdab-4a2c-b9e5-9877a5d86a96.png)
