### ISSUE TITLE
Edit attributes from Content type

### ISSUE THREAD

**Issue by angeli-mercedes** [klaudsol/klaudsol-cms#63]
Upon clicking this button

![Image](https://user-images.githubusercontent.com/101687552/207742821-4543c634-f0e8-40fb-8ceb-4886313a9bee.png)

Show a modal similar to this

![Image](https://user-images.githubusercontent.com/101687552/207743021-c20455ad-ce3a-4352-89d8-c6985420dd55.png)

Note:
- Short Text and Long Text boxes are buttons
- If Short Text is clicked - attribute will change to text
- If Long Text is clicked - attribute will change to textarea

**Comment by ardeearam** [comment]
I shall create a V1 for this (a more straightforward interface with a dropdown for selecting the content type).

Feel free to implement the modal above.
